### PR TITLE
Add color icons for tab bar

### LINKED ISSUE #126: Change icons in the tab bar

### PR DESCRIPTION
**Pull request by prelangi**
Closes #126

### CODE REVIEW

**Comment by prelangi** [comment]
image

**Comment by prelangi** [comment]
@mahagovind @vnu : Take a look at the new tab bar.

**Comment by vnu** [comment]
@prelangi It looks good. But couple issues. user search looks like a guy considering its women who code app. We need to change that one.

**Comment by prelangi** [comment]
@vnu : Yeah they only had a male image :( I put in a request for the user search with a female profile. 

The default search icon was also blue so did not put that (the whole tab bar has lots of blue). I will look for a search icon with other colors meanwhile.

**Pull request merged**
